# Exceptions
In .NET an exception is essentially a class.

Exception parts when thrown:
1. The error message
2. Stack trace: Shows a backtrack of functions that were executed untill the exception was thrown starting from the method that threw the exception

![d2bc82ea04f7cd40888dbec2c3dea341.png](d2bc82ea04f7cd40888dbec2c3dea341.png)

# Handling Exceptions
We use `try/catch` blocks. We put the code in a `try` block. if an exception is thrown the catch block will be executed. 
in a catch block we have 2 choices:
* Recover from the error and prevent the application from crashing
* Throw the error back to the caller of the error

Its good practice to always have a global exception handling block in our application.

The `Exception` Class is the parent of all exceptions in .NET.
Exception object properties:
* `Message`: The error that is associated with the exception.
* `Source`: Name of the app that generated the error.
* `StackTrace`: The sequence of method calls in reverse order.
* `TargetSite`: The method were the exception happened.
* `InnerException`: Could be an exception that accured inside this exception.
* `Data`: Carries additional data about the exception.

## Multiple Catch Blocks
We can have multiple catch blocks going from ***most specific to most generic***

![d949f1735732cb3cd89dd1abc69848e7.png](d949f1735732cb3cd89dd1abc69848e7.png)

The order is important, because parent classes will catch all specific exceptions and won't allow us to catch them.

## Finally Block
`finally()` will always be executed.
In .NET we have classes that access unmanaged resources(recources that are managed by the CLR). So they don't have garbage collection applied to them. Like:
* File Handles
* Database Connections
* Netowrk Connections
* Graphic Handles

Any class that uses unmanaged resources is expected to implement an Interface called `IDisposable`.
We the `finally` block to call the `Dispose()` method of the unmanaged resource.
when working with classes that have unmanaged resources its very important to dispose them because they occupy resources. So, no matter what happens we want to make sure that the object is disposed.

The `try{}` block has different scope than `finally{}`. So in order to use the `Dispose()` method, we have to declare it in a higher scope than out exception handler and initialize it to `null`.  Then in our `finally` block, we have to check if the object is not `null` before calling the `Dispose()` method.

![296994742cba71046ba9a877e98b63e6.png](296994742cba71046ba9a877e98b63e6.png)

## Using
Instead of declaring a variable outside a `try` block, then initialize it inside it, then in `finally` checking for `null` and dispose it, we can use `using`.
So the code above would look like this:

![ea978a452520624708bd27ab45204af5.png](ea978a452520624708bd27ab45204af5.png)

When using this statement, under the hood, the compiler will create `finally` and it will call the dispose method of the object.

# Custom Exceptions
In a custom class there can be a lot of reasons that something can go wrong. In those situations, we can throw low level exceptions like parsing or network exceptions. We don't want to expose these lower level exceptions to the higher level of our application. In such situations we create a custom exception.

To do that we create a class and it should derive from `Exception`.
In the calss' constructor we need 2 objects:
1. `string message`
2. `Exception innerException`

And we must pass it to the base constructor of the `Exception` class.

So when something goes wrong in our program, we catch it in our catch block with `catch(Exception ex)`, then we can pass the exception to our custom handler.

```C#
catch(Exception ex)
{
	throw new CustomException("Message", ex);
}
```

When this new exception will be part of our innerException.